name: Deploy to Play Store

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: android

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/android/app/unfilter-release.jks

      - name: Install dependencies
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/android/app/unfilter-release.jks
          ANDROID_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter pub get

      - name: Build Android AppBundle (AAB)
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/android/app/unfilter-release.jks
          ANDROID_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build appbundle --release

      - name: Create Play Store Service Account JSON
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        run: |
          echo "$PLAY_STORE_CONFIG_JSON" > android/play_store_config.json

      - name: Run Fastlane Deployment
        env:
          PLAY_STORE_CONFIG_JSON_PATH: "../play_store_config.json"
        working-directory: android
        run: bundle install && bundle exec fastlane deploy

